# Generated by Django 4.2.10 on 2026-05-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiningProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('location', models.CharField(help_text='e.g., Chunya, Geita, Handeni', max_length=150)),
                ('stage', models.CharField(choices=[('grassroots', 'Grassroots Exploration'), ('advanced', 'Advanced Exploration'), ('feasibility', 'Feasibility Study'), ('production', 'Production')], max_length=20)),
                ('description', models.TextField()),
                ('commodity', models.CharField(default='Gold', max_length=100)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('testimonial', models.TextField(blank=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='projects/')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='List of Cloudinary URLs')),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
