# Generated by Django 4.2.10 on 2026-05-22 11:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miningproject',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Mining Project', 'verbose_name_plural': 'Mining Projects'},
        ),
        migrations.AlterField(
            model_name='miningproject',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
