# Generated by Django 4.2.10 on 2026-05-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_miningproject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miningproject',
            options={'ordering': ['order', '-created_at']},
        ),
    ]
