# Generated by Django 4.2.10 on 2026-05-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('news', 'Company News & Blog'), ('csr', 'Corporate Social Responsibility (CSR)')], max_length=10)),
                ('content', models.TextField()),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='media_posts/')),
                ('author', models.CharField(default='Golden Expro Team', max_length=100)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
