# Generated by Django 4.2.10 on 2026-05-22 11:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapost',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
