# Generated by Django 4.2.10 on 2026-05-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycontent',
            options={'verbose_name': 'Company Content', 'verbose_name_plural': 'Company Contents'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ['order'], 'verbose_name': 'Statistic', 'verbose_name_plural': 'Statistics'},
        ),
        migrations.AlterField(
            model_name='statistic',
            name='icon_class',
            field=models.CharField(blank=True, help_text="FontAwesome icon class (e.g., 'fas fa-chart-bar')", max_length=50),
        ),
    ]
